# Generated by Django 4.2.1 on 2023-05-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='scheduleufa',
            options={'verbose_name_plural': 'Расписание выездов'},
        ),
        migrations.RemoveField(
            model_name='driver',
            name='car',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='person',
        ),
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
