# Generated by Django 4.2.1 on 2023-05-16 17:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_city_client_drive_employee_alter_driver_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_phone', models.CharField(max_length=20)),
                ('client_name', models.CharField(blank=True, default='', max_length=100)),
                ('total_price', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(9999)])),
                ('min_time', models.TimeField()),
                ('max_time', models.TimeField()),
                ('start_address', models.CharField(max_length=250)),
                ('finish_address', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name_plural': 'Маршруты — время'},
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='dep_time',
            new_name='time',
        ),
        migrations.AlterUniqueTogether(
            name='drive',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='driver',
            name='car',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='client',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='finish_address',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='route',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='start_address',
        ),
        migrations.AddField(
            model_name='city',
            name='dist_parent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='city',
            name='est_time_addition',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='parent_city_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='price_addition',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='drive',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='drives', to='main.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drive',
            name='scheduled_route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='main.route'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='times', to='main.route'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stops',
            name='address',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='dist_ufa',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='drive',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='main.driver'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passengers', to='main.drive'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='est_dep_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='finish_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_routes', to='main.city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='price',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_routes', to='main.city'),
        ),
        migrations.AlterField(
            model_name='stops',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='main.city'),
        ),
        migrations.AlterUniqueTogether(
            name='drive',
            unique_together={('scheduled_route', 'driver', 'car')},
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='booking',
            name='finish_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_bookings', to='main.city'),
        ),
        migrations.AddField(
            model_name='booking',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.route'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_bookings', to='main.city'),
        ),
        migrations.RemoveField(
            model_name='drive',
            name='route',
        ),
        migrations.RemoveField(
            model_name='drive',
            name='start_time',
        ),
        migrations.AddField(
            model_name='passenger',
            name='booking',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='main.booking'),
            preserve_default=False,
        ),
    ]
