# Generated by Django 4.2.1 on 2023-05-20 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_booking_alter_driver_options_alter_route_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name_plural': 'Водители'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='dist_parent',
        ),
        migrations.AlterField(
            model_name='city',
            name='price_addition',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
