# Generated by Django 4.2.1 on 2023-05-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_area_remove_city_est_time_addition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='est_dep_time',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
