# Generated by Django 4.2.1 on 2023-05-23 17:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_max_time_booking_time_remove_booking_min_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='ScheduledRoute',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='route',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(1997, 10, 19)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='main.scheduledroute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drive',
            name='date',
            field=models.DateField(default=datetime.date(1997, 10, 19)),
            preserve_default=False,
        ),
    ]
