# Generated by Django 4.2.1 on 2023-05-23 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_schedule_scheduledroute_remove_booking_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='scheduled_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='main.scheduledroute'),
        ),
    ]
