# Generated by Django 4.2.1 on 2023-05-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_drive_scheduled_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='est_time_ufa',
            field=models.TimeField(),
        ),
    ]
