# Generated by Django 4.2.1 on 2023-05-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_city_est_time_ufa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
